"Snippet with title"
type CodeBox {
	Title: String!
	Code: String!
}
"Language with snippets"
type Language {
	LangName: String!
	CodeBoxes: [CodeBox]!
}
"Returns status and message"
type Signal {
	Status: Int!
	Message: String!
}
schema {
	query: Query
	mutation: Mutation
}
type Query {
	"All Languages and their snippets"
	langList: [Language!]!
	"Snippets of a selected language"
	langFind(langName: String!): Language!
	"Finds all snippets similar to given title"
	titleFind(title: String!): [Language!]
	"All languages snippets are avaliable in"
	langNames: [String!]!
}
type Mutation {
	"User Snippet api function"
	snipAdd(codeSnip: SnipBox!): Signal!
}
"Language With snippet to be added"
input SnipBox {
	LangName: String!
	CodeBox: CodeBlock!
}
"Snippet to be added"
input CodeBlock {
	Title: String!
	Code: String!
}
