// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Snippet to be added
type CodeBlock struct {
	Title string `json:"title"`
	Code  string `json:"code"`
}

// Snippet with title
type CodeBox struct {
	Title string `json:"title"`
	Code  string `json:"code"`
}

// Language with snippets
type Language struct {
	LangName  string     `json:"langName"`
	CodeBoxes []*CodeBox `json:"codeBoxes"`
}

type Mutation struct {
}

type Query struct {
}

// Returns status and message
type Signal struct {
	Status  int    `json:"status"`
	Message string `json:"message"`
}

// Language With snippet to be added
type SnipBox struct {
	LangName string     `json:"langName"`
	CodeBox  *CodeBlock `json:"codeBox"`
}
